### ISSUE TITLE
Disable global address book for some users

### ISSUE THREAD

**Issue by horosgrisa** [JohnDoh/Roundcube-Plugin-Global-Address-Book#38]
You can add option for disabling address book ( or address completion ) in control panel?

**Comment by JohnDoh** [comment]
I'm not sure what you mean by control panel, there is no admin type control panel in Roundcube. In any case the function would be beyound the scope of this plugin as it is safer to achieve such a thing by controlling which plugins are loaded for specific users rather than telling the plugin to hide itself.
